apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-pvc
  namespace: cloud-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cloud-sc
